# autoupdate is a GitHub Action that auto-updates pull requests branches whenever changes land on their destination branch.
name: autoupdate
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ secrets.PROBE_APP_ID }}
          private-key: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
          owner: TykTechnologies

      - uses: docker://chinthakagodawita/autoupdate-action:v1@sha256:53d7013ad4689b703d2715d4b17d4901bb0a385e495e0b481f37adbe9b3cc3fc
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          # Only monitor PRs that are not currently in the draft state.
          PR_READY_STATE: "ready_for_review"
          MERGE_CONFLICT_ACTION: "ignore"  # Possible option to prevent retrying failed merges
