name: Link Checker

on:
  pull_request:
    paths:
      - '**.md'
      - '**.mdx'
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config ./lychee.toml
            --verbose
            --include-fragments
            --no-progress
            '**/*.md'
            '**/*.mdx'
          fail: true
